###############################################################################
# Build the Entire App
#
# Am using volumes in this Dev environment to allow sppedy dev
# Rather than having to rebuild images and deploy new containers
#
###############################################################################

version: '2'
services:
 
  # The Origional Quote Service
  quotes:
    hostname: servicequote
    volumes:
      - ./ServiceQuote/main.py:/usr/src/app/main.py
    build:
      context: ./ServiceQuote
      dockerfile: app.dockerfile
      
  # New Test Service
  test:
    hostname: servicetest
    volumes:
      - ./ServiceTest/main.py:/usr/src/app/main.py
    build:
      context: ./ServiceTest
      dockerfile: app.dockerfile

  # News Service
  news:
    hostname: servicenews
    volumes:
      - ./ServiceNews/main.py:/usr/src/app/main.py
    build:
      context: ./ServiceNews
      dockerfile: app.dockerfile

  # The API GateWay Service
  api:
    hostname: apigateway
    environment:
      - "QUOTES_API=http://quotes:5000"
      - "TEST_API=http://test:5001"
      - "NEWS_API=http://news:5002"
    volumes:
      - ./ApiGateway/index.js:/usr/src/app/index.js
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    depends_on:
      - quotes
      - test
      - news
    ports:
      - "3000:3000"

  # The UI Front End Service
  frontend:
    hostname: uiserver
    volumes:
      - ./FrontendApplication/dist/index.html:/var/www/index.html
      - ./FrontendApplication/dist/main.js:/var/www/main.js
    build:
      context: ./FrontendApplication
      dockerfile: app.dockerfile
    ports:
      - "8080:80"
    